apiVersion: apps/v1
kind: Deployment
metadata:
  name: saludoapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: saludoapp
  template:
    metadata:
      labels:
        app: saludoapp
    spec:
      containers:
      - name: saludoapp
        image: fredyball/saludoapp:0.0.1
        ports:
        - containerPort: 80
