---
apiVersion: v1
kind: Service
metadata:
  name: saludoapp-service
spec:
  selector:
    app: saludoapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort